In [10]:
# regular python - lists
list1 = [1, 2, 6, 7]

1

In [22]:
# iterate the list
for i in range(len(list1)):
    print(list1[i]+5)

6
7
11
12


In [15]:
f = lambda x: x**2
new_list = list(map(f, list1))
new_list

[1, 4, 36, 49]

In [21]:
# indexing
# name_list[inclusive : exclusive]
list1[1: 3]

[2, 6]

In [31]:
# string lists
# strings

string = "string" # collection of characters
string1 = "s" + "t" + "r"

names = ["Joe", "Alex", "Ann", "James", "Fred"]

In [34]:
# only the name starting with "J"
g = lambda x: x if x[0] == "J" else None
new_namelist = list(map(g, names))
new_namelist

['Joe', None, None, 'James', None]

In [35]:
import numpy as np

In [37]:
v = np.random.rand(1, 5)
v

array([[0.86706381, 0.1351544 , 0.44569247, 0.39830239, 0.43688747]])

In [60]:
# vector[rows][columns]
v[0][1:-1]

array([0.1351544 , 0.44569247, 0.39830239])

In [63]:
A = np.random.rand(3, 3)
A

array([[0.10536691, 0.83524162, 0.04434241],
       [0.12159441, 0.04784844, 0.15047218],
       [0.35584727, 0.56867313, 0.95114558]])

In [70]:
# Matrix[rows, columns]

In [71]:
# vector[rows, columns]
v

array([[0.86706381, 0.1351544 , 0.44569247, 0.39830239, 0.43688747]])

In [115]:
threshold = 0.3
h = lambda x: x if x > threshold else None

In [132]:
x = []
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        x.append(h(A[i][j]))
X = np.array([x])
X

array([[None, 0.8352416170909945, None, None, None, None,
        0.35584727177347086, 0.5686731345636141, 0.9511455807804383]],
      dtype=object)

In [137]:
A[(A>0.3)*(A<0.4)]

array([0.35584727])

In [143]:
J = np.random.rand(1, 2, 5)
J

array([[[0.79845661, 0.37497778, 0.40055449, 0.48942082, 0.20262088],
        [0.8337976 , 0.56122517, 0.31127867, 0.44426252, 0.7947528 ]]])

In [146]:
# J[layer][rows][columns]

In [147]:
J[0][0][0]

0.7984566105122642

In [170]:
J[0][0]

array([0.79845661, 0.37497778, 0.40055449, 0.48942082, 0.20262088])